#
# Configure virtualenv
#

- name: virtualenv | create ~/.virtualenvs directory
  file: 'name={{ ansible_env.HOME }}/.virtualenvs state=directory'

- name: virtualenv | create scripts
  copy: 'src={{ item }} dest={{ ansible_env.HOME }}/.virtualenvs/{{ item }} mode=0755'
  with_items:
    - postmkvirtualenv

#
# Install pipsi - https://github.com/mitsuhiko/pipsi
#
# This does much the same things as the `get-pipsi.py` script
#

- name: pipsi | create virtualenv
  command: 'virtualenv {{ pipsi_venv }}'
  args: {'creates': '{{ pipsi_venv }}/bin/python'}

- name: pipsi | install pipsi
  pip: 'name=pipsi state=latest virtualenv={{ pipsi_venv }}'

- name: pipsi | create pipsi bin directory
  file: 'name={{ pipsi_bin }} state=directory'

- name: pipsi | link pipsi
  file: 'src={{ pipsi_venv }}/bin/pipsi dest={{ pipsi_bin }}/pipsi state=link'

- name: pipsi | install python tools with pipsi
  pipsi: "name={{ item }} state=present"
  with_items:
    - tox
    - fig
    - sphinx
    - v
    - restructuredtext-lint
