---
- name: zsh | install
  apt: pkg=zsh state=latest
  sudo: yes

- name: zsh | copy configuration
  copy: 'src=zsh/ dest={{ zsh_home }}/'

- name: zsh | link ~/.zshrc
  file: 'src={{ zsh_home }}/zshrc dest={{ ansible_env.HOME }}/.zshrc state=link'

- name: zsh | link ~/.zshenv
  file: 'src={{ zsh_home }}/zshenv dest={{ ansible_env.HOME }}/.zshenv state=link'

- name: zsh | set user shell
  user: 'name={{ ansible_ssh_user }} shell=/bin/zsh'
  sudo: yes
