---
- name: zsh | install
  apt: pkg=zsh state=latest
  sudo: yes

- name: zsh | configure
  template: 'src=zshrc dest={{ ansible_env.HOME }}/.zshrc'
  tags:
    - dotfiles

- name: zsh | configure environment
  template: 'src=zshenv dest={{ ansible_env.HOME }}/.zshenv'
  tags:
    - dotfiles

- name: zsh | create cache directory
  file: 'path={{ ansible_env.HOME }}/.cache/zsh/ state=directory'

- name: zsh | set user shell
  user: 'name={{ ansible_ssh_user }} shell=/bin/zsh'
  sudo: yes
