#
# Install user-specific configuration to $HOME
#
# This assumes that the remote ansible user is the user configuration should
# be deployed to.
#

- include: "lang-python.yml tags=python,pipsi"
- include: "lang-ruby.yml tags=ruby"
- include: "lang-zsh.yml tags=zsh,shell"

- include: "tool-peru.yml tags=peru"
  when: ansible_distribution != 'Debian' # TODO: Doesn't have Python >= 3.3

- name: configure dotfiles
  template: >
    src={{ item }}
    dest={{ ansible_env.HOME }}/.{{ item }}
  with_items:
    - gitconfig
    - gitignore
    - htoprc
    - nanorc
    - tmux.conf
  tags: dotfiles

#
# Installs scripts to ~/.local/bin
#

- name: bin | create directory
  file: >
    name={{ ansible_env.HOME }}/.local/bin
    state=directory

- name: bin | install scripts
  copy: >
    src=local/bin/{{ item }}
    dest={{ ansible_env.HOME }}/.local/bin/{{ item }}
    mode=0755
  sudo: yes
  with_items:
    - ansible-run
    - git-hub
    - git-overwritten
    - git-tag-version
    - gws
    - hub
    - tmux-attach
