#
# Tasks that should be run on all hosts
#

# - include: "os-debian.yml tags=debian"
#   when: ansible_distribution == 'Debian'

# - include: "os-ubuntu.yml tags=ubuntu"
#   when: ansible_distribution in ['Ubuntu', 'Linuxmint']

- name: generate ssh key
  user: 'name={{ ansible_ssh_user }} generate_ssh_key=true'
  sudo: yes

- name: install utility packages
  apt: 'pkg={{ item }} state=latest'
  sudo: yes
  with_items:
    - htop
    - nano
    - tmux
    - tree
    - aptitude
