#
# Install other packages
#

- name: install utility packages
  apt: 'pkg={{ item }} state=latest'
  become: yes
  with_items:
    - aptitude
    - htop
    - jq
    - multitail
    - nano
    - realpath
    - tmux
    - tree
  tags:
    - bin
    - util

#
# Install programming languages and packages from their repositories
#

- name: go
  include: lang-go.yml
  tags: ['languages', 'go']
- name: node
  include: lang-node.yml
  tags: ['languages', 'node']
- name: python
  include: lang-python-deadsnakes.yml
  tags: ['languages', 'python', 'deadsnakes']
- name: python
  include: lang-python.yml
  tags: ['languages', 'python']
- name: ruby
  include: lang-ruby.yml
  tags: ['languages', 'ruby']

#
# Install services
#

- name: supervisor
  include: service-supervisor.yml
  tags: ['services', 'supervisor']

#
# Install development tools
#

- name: ack
  include: tool-ack.yml
  tags: ['tools', 'ack']
- name: ansible
  include: tool-ansible.yml
  tags: ['tools', 'ansible']
- name: blink1
  include: tool-blink1.yml
  tags: ['tools', 'blink1']
- name: chefdk
  include: tool-chefdk.yml
  tags: ['tools', 'chefdk', 'chef']
- name: docker
  include: tool-docker.yml
  tags: ['tools', 'docker']
- name: git
  include: tool-git.yml
  tags: ['tools', 'git']
- name: nix
  include: tool-nix.yml
  tags: ['tools', 'nix']
