#
# Install git.
#

- include: >
    ../../../tasks/apt.yml
    name=git
    url='deb http://ppa.launchpad.net/git-core/ppa/ubuntu trusty main'
    key=E1DF1F24

- name: git | install
  apt: pkg=git state=latest
  sudo: yes

# - name: git | link git-subtree
#   file: >
#     src=/usr/share/doc/git/contrib/subtree/git-subtree.sh
#     dest=/usr/local/bin/git-subtree
#     state=link
#     force=yes
#   sudo: yes
