#
# Installs the Nix package manager
#

- name: nix | install package
  include: >
    ../../../tasks/deb.yml
    name=nix
    version=1.10.0
    url=http://hydra.nixos.org/build/25489743/download/1/nix_1.10-1_amd64.deb
