---
- name: zsh | install
  apt: pkg=zsh state=latest
  sudo: yes

- name: zsh | copy configuration
  copy: >
    src=local/share/zsh/
    dest={{ ansible_env.HOME }}/.local/share/zsh/
  tags:
    - dotfiles
    - zshrc

- name: zsh | link ~/.zshrc
  file: >
    src={{ ansible_env.HOME }}/.local/share/zsh/zshrc
    dest={{ ansible_env.HOME }}/.zshrc
    state=link
  tags:
    - dotfiles
    - zshrc

- name: zsh | link ~/.zshenv
  file: >
    src={{ ansible_env.HOME }}/.local/share/zsh/zshenv
    dest={{ ansible_env.HOME }}/.zshenv
    state=link
  tags:
    - dotfiles
    - zshrc

- name: zsh | set user shell
  user: >
    name={{ ansible_ssh_user }}
    shell=/bin/zsh
  sudo: yes
