#
# Install user-specific configuration to $HOME
#
# This assumes that the remote ansible user is the user configuration should
# be deployed to.
#

- include: "lang-python.yml tags=python,virtualenv"
- include: "lang-ruby.yml tags=ruby"
- include: "lang-zsh.yml tags=zsh,shell"
- include: "tool-peru.yml tags=peru"

- name: generate ssh key
  user: 'name={{ ansible_ssh_user }} generate_ssh_key=true'

- name: configure dotfiles
  template: >
    src={{ item }}
    dest={{ ansible_env.HOME }}/.{{ item }}
  with_items:
    - gitconfig
    - gitignore
    - htoprc
    - nanorc
    - tmux.conf
  tags: dotfiles

#
# Installs scripts to ~/.local/bin
#

- name: create bin directory
  file: >
    name={{ ansible_env.HOME }}/.local/bin
    state=directory

- name: install executables and scripts
  copy: >
    src=local/bin/{{ item }}
    dest={{ ansible_env.HOME }}/.local/bin/{{ item }}
    mode=0755
  with_items:
    - ansible-run
    - blink1-tool
    - caddy
    - docker-gc
    - git-cleanup
    - git-hub
    - git-overwritten
    - git-sync
    - git-tag-version
    - gws
    - hub
    - tmux-attach
    - wago
  tags:
    - bin
    - blink
    - git
