#
# Install Python 2.6 and 3.3 using the deadsnakes PPA
#
# Install the deadsnakes PPA with:
#
#   apt-add-repository --yes ppa:fkrull/deadsnakes
#

- name: install python2.6 and python3.3 from deadsnakes
  apt: 'pkg={{ item }} state=latest'
  sudo: yes
  with_items:
    - python2.6
    - python2.6-dev
    - python3.3
    - python3.3-dev
