#
# Install Ruby
#
# The ruby-nokogiri package is installed because many gems depend on it, and
# it had a complicated mix of install/compile time dependencies usually break.
#

- include_vars: 'lang-ruby-{{ ansible_distribution | lower }}.yml'

- name: install ruby
  apt: 'pkg={{ item }} state=latest'
  sudo: yes
  with_items: ruby_packages

- name: install ruby-nokogiri
  apt: 'pkg=ruby-nokogiri state=latest'
  sudo: yes
