#
# Install docker
#

- name: docker | install
  apt: 'pkg=docker.io state=latest'
  sudo: yes

# https://github.com/docker/docker/issues/4734
- name: docker | install useful packages
  apt: 'pkg={{ item }} state=latest'
  sudo: yes
  with_items:
    - apparmor
    - cgroup-lite

- name: docker | add user to docker group
  user: 'name={{ ansible_ssh_user }} groups=docker append=true'
  sudo: yes
