#
# Github helper
#
# https://github.com/github/hub
#
# Cleanup from previous versions:
# $ rm /usr/local/bin/git-hub
#

- name: hub | install
  copy: 'src=hub dest=/usr/local/bin/hub mode=0755'
  sudo: yes
  tags: peru

- name: hub | link hub to git-hub
  file: 'src=/usr/local/bin/hub dest=/usr/local/bin/git-hub state=link'
  sudo: yes

- name: hub | add completion
  copy: 'src=hub.zsh dest=/usr/local/share/zsh/site-functions/hub.zsh mode=0755'
  sudo: yes
  tags: peru
