---

- hosts: all
  roles:
    - role: base
      tags: base
    - role: user
      tags: user
    - role: development
      tags: development

- hosts: workstation
  roles:
    - role: workstation
      tags: workstation

- hosts: servers
  roles:
    - role: server
      tags: server
