---

- hosts: all
  roles:
    - { role: base-debian, tags: ['base'], when: ansible_os_family == 'Debian' }
    - { role: base, tags: ['base'] }

- hosts: workstation
  roles:
    - { role: workstation, tags: ['workstation'] }
    - { role: riemann, tags: ['riemann'] }

- hosts: servers
  roles:
    - { role: server, tags: ['server'] }
