---

- hosts: all
  roles:
    - role: stage1-base
      tags: stage1-base
    - role: stage2-development
      tags: stage2-development
    - role: stage3-user
      tags: stage4-user

- hosts: workstation
  roles:
    - role: workstation
      tags: workstation

- hosts: webserver
  roles:
    - role: webserver
      tags: webserver
