#
# Install local gems
#

- include_vars: 'lang-ruby-{{ ansible_distribution | lower }}.yml'

- name: install ruby packages
  gem: 'state=latest name={{ item }} executable={{ gem }} user_install=yes'
  with_items:
    - github-pages
    - travis
    - travis-lint
    - fpm
