#
# Installs Ansible from the upstream PPA
#

- name: configure ansible ppa
  command: apt-add-repository ppa:ansible/ansible
  args: {'creates': '/etc/apt/sources.list.d/ansible-ansible-trusty.list'}
  tags:
    - ansible

- name: update ansible
  apt: pkg=ansible state=latest
  tags:
    - ansible
