---
- name: install common software
  apt: pkg={{ item }} state=latest
  with_items:
    - firefox
    - terminator

- name: install development software
  apt: pkg={{ item }} state=latest
  with_items:
    - ruby
    - ruby-dev
    - python
    - python-dev
    - python3
    - python3-dev
    - git
    - ansible

- name: configure dotfiles
  template: src={{ item }} dest=~/.{{ item }}
  with_items:
    - 'gitconfig'

- gem: name=git-hub state=latest
