#
# Install software only useful on a workstation or non-headless machine
#

- name: install common software
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - firefox
    - terminator
    - git-cola
    - gitg
    - meld
    - crawl-tiles
    - keepassx
    - dropbox
    - nemo-dropbox
    - sublime-text
    - steam-launcher

#
# Spotify Linux preview
#

- name: spotify | add repository
  apt_repository: repo='deb http://repository.spotify.com stable non-free' state=present
  register: spotify_repository
  sudo: yes

- name: spotify | add repository key
  apt_key: id=94558F59 keyserver=hkp://keyserver.ubuntu.com:80
  register: spotify_repository_key
  sudo: yes

- name: spotify | update repositories
  apt: 'update_cache=yes'
  when: spotify_repository.changed or spotify_repository_key.changed
  sudo: yes

- name: spotify | install package
  apt: 'pkg=spotify-client state=installed'
  sudo: yes

#
# Ansible
#

- name: add ansible PPA
  command: apt-add-repository ppa:ansible/ansible
  args: {'creates': '/etc/apt/sources.list.d/ansible-ansible-trusty.list'}
  when: ansible_distribution in ['Ubuntu', 'Linuxmint']
  sudo: yes

- name: install ansible
  apt: pkg=ansible state=latest
  sudo: yes
