#
# Install software only useful on a workstation or non-headless machine
#

- include: "app-atom.yml tags=atom"
- include: "app-jetbrains.yml tags=jetbrains"
- include: "app-slack.yml tags=slack"
- include: "app-spotify.yml tags=spotify"
- include: "app-sublime.yml tags=sublime"
- include: "app-terminator.yml tags=terminator"

- name: install personal software
  apt: "pkg={{ item }} state=latest"
  sudo: yes
  with_items:
    - firefox
    - keepassx
    - gparted

- name: install dropbox
  apt: "pkg={{ item }} state=latest"
  sudo: yes
  with_items:
    - dropbox
    - nemo-dropbox

- name: install development software
  apt: "pkg={{ item }} state=latest"
  sudo: yes
  with_items:
    - git-cola
    - gitg
    - meld

- name: install games and steam
  apt: "pkg={{ item }} state=latest"
  sudo: yes
  with_items:
    - steam-launcher
    - crawl-tiles
    - mumble

- name: configure XDG directories
  template: >
    dest={{ ansible_env.HOME }}/.config/user-dirs.dirs
    src=user-dirs.dirs
  tags:
  - xdg
