---
- include: "development.yml tags=development,dev"
- include: "ansible.yml tags=ansible"
- include: "python.yml tags=python"
- include: "shell.yml tags=shell"

- name: install common software
  apt: pkg={{ item }} state=latest
  with_items:
    - firefox
    - terminator
  tags:
    - gui

- name: configure terminator
  template: dest=~/.config/terminator/config src=terminator.conf
  tags:
    - dotfiles
    - gui
