#
# Installs and configures development tools
#

- name: install development packages
  apt: 'pkg={{ item }} state=latest'
  sudo: yes
  with_items:
    - ack-grep
    - git
    - htop
    - nano
    - ruby
    - ruby-dev
    - tmux
    - tree

- name: check if /usr/bin/ack exists
  stat: path=/usr/bin/ack
  register: ack

- name: link ack-grep to ack-grep
  command: dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep
  when: not ack.stat.exists
  sudo: yes

- name: install nodejs
  apt: 'pkg={{ item }} state=latest'
  when: ansible_distribution != 'Debian' or ansible_distribution_release != 'wheezy'
  sudo: yes
  with_items:
    - nodejs
    - nodejs-legacy
    - npm

- name: install nodejs from wheezy-backports
  apt: 'pkg={{ item }} state=latest default_release=wheezy-backports'
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'wheezy'
  sudo: yes
  with_items:
    - nodejs
    - nodejs-legacy

- name: install git scripts
  copy: 'src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755'
  sudo: yes
  with_items:
    - git-hub
    - git-tag-version
    - git-overwritten

- name: link git-subtree
  file: 'src=/usr/share/doc/git/contrib/subtree/git-subtree.sh dest=/usr/local/bin/git-subtree state=link force=yes'
  sudo: yes

- name: install development gems
  gem: 'state=latest name={{ item }}'
  with_items:
    - jekyll
    - travis
    - travis-lint
  tags:
    - ruby
    - slow
