#
# Installs and configures development tools
#

- name: install development packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - ack-grep
    - git
    - htop
    - nano
    - nodejs
    - ruby
    - ruby-dev
    - tmux
    - tree

- name: install git scripts
  copy: 'src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755'
  sudo: yes
  with_items:
    - git-tag-version
    - git-overwritten

- name: link git-subtree
  file: 'src=/usr/share/doc/git/contrib/subtree/git-subtree.sh dest=/usr/local/bin/git-subtree state=link'
  sudo: yes

- name: install development gems
  gem: 'state=latest name={{ item }}'
  sudo: yes
  with_items:
    - git-hub
    - jekyll
    - travis
    - travis-lint
  tags:
    - ruby
