#
# Prepares a Python development environment
#

- name: install python packages
  apt: 'pkg={{ item }} state=latest'
  sudo: yes
  with_items:
    - python
    - python-pip
    - python-dev
    - python3
    - python3-pip
    - python3-dev
    - virtualenvwrapper

#
# Install virtualenv and virtualenvwrapper
#

- name: virtualenv | install packages
  apt: 'pkg={{ item }} state=latest'
  sudo: yes
  with_items:
    - python-virtualenv
    - virtualenvwrapper

- name: virtualenv | create ~/.virtualenvs directory
  file: 'name={{ ansible_env.HOME }}/.virtualenvs state=directory'

- name: virtualenv | create scripts
  copy: 'src={{ item }} dest={{ ansible_env.HOME }}/.virtualenvs/{{ item }} mode=0755'
  with_items:
    - postmkvirtualenv

#
# Install pipsi - https://github.com/mitsuhiko/pipsi
#

- name: pipsi | create virtualenv
  command: 'virtualenv {{ pipsi_venv }}'
  args: {'creates': '{{ pipsi_venv }}/bin/python'}

- name: pipsi | install pipsi
  pip: 'name=pipsi state=latest virtualenv={{ pipsi_venv }}'

- name: pipsi | create pipsi bin directory
  file: 'name={{ pipsi_bin }} state=directory'

- name: pipsi | link pipsi
  file: 'src={{ pipsi_venv }}/bin/pipsi dest={{ pipsi_bin }}/pipsi state=link'
