#
# Prepares a Python development environment
#

- name: configure deadsnakes ppa
  when: ansible_distribution == 'Ubuntu'
  command: apt-add-repository ppa:fkrull/deadsnakes
  args: {'creates': '/etc/apt/sources.list.d/fkrull-deadsnakes-trusty.list'}

- name: install python packages
  apt: 'pkg={{ item }} state=latest'
  with_items:
    - python
    - python-pip
    - python-dev
    - python-flake8
    - python-setuptools
    - python3
    - python3-pip
    - python3-dev
    - python3-flake8
    - python3-setuptools
    - virtualenvwrapper

- name: install deprecated python packages
  when: ansible_distribution == 'Ubuntu'
  apt: 'pkg={{ item }} state=latest'
  with_items:
    - python2.6
    - python2.6-dev

# - name: install python development modules (py3)
#   pip: 'state=latest executable=pip3 name={{ item }}'
#   with_items:
#     - tox
#     - pyyaml

- name: install postmkvirtualenv script
  copy: src=postmkvirtualenv dest=~/.virtualenvs/postmkvirtualenv mode=0755
