#
# Prepares a Python development environment
#

- name: install python packages
  apt: 'pkg={{ item }} state=latest'
  with_items:
    - python
    - python-pip
    - python-dev
    - python3
    - python3-pip
    - python3-dev

- name: deadsnakes | configure ppa
  when: ansible_distribution == 'Ubuntu'
  command: apt-add-repository ppa:fkrull/deadsnakes
  args: {'creates': '/etc/apt/sources.list.d/fkrull-deadsnakes-trusty.list'}

- name: deadsnakes | install python2.6
  when: ansible_distribution == 'Ubuntu'
  apt: 'pkg={{ item }} state=latest'
  with_items:
    - python2.6
    - python2.6-dev

- name: virtualenv | install packages
  apt: 'pkg={{ item }} state=latest'
  with_items:
    - python-virtualenv
    - virtualenvwrapper

- name: virtualenv | create scripts
  copy: src=postmkvirtualenv dest=~/.virtualenvs/postmkvirtualenv mode=0755
