---
- name: modify users
  user: >
    name='{{ item.key }}'
    comment='{{ item.value.comment }}'
    shell='{{ item.value.shell }}'
    generate_ssh_key=true
    groups=sudo
    append=true
  sudo: yes
  with_dict: users

- name: create user www paths
  file: >
    path=/var/www/{{ item }}
    owner={{ item }}
    group={{ item }}
    state=directory
  sudo: yes
  with_items: users.keys()

- name: install nginx
  apt: pkg=nginx state=latest
  sudo: yes
  tags:
    - nginx

- name: configure sites
  sudo: yes
  template: >
    src=site-{{ item.key }}.conf
    dest=/etc/nginx/sites-available/{{ item.key }}.conf
    owner={{ item.value.user }}
    group={{ item.value.user }}
  with_dict: nginx_sites
  register: nginx_config
  tags:
    - nginx

- name: enable sites
  sudo: yes
  file: >
    src=/etc/nginx/sites-available/{{ item.key }}.conf
    dest=/etc/nginx/sites-enabled/{{ item.key }}.conf
    state=link
    force=yes
  with_dict: nginx_sites
  register: nginx_enabled_sites
  tags:
    - nginx

- name: restart nginx
  when: nginx_config.changed or nginx_enabled_sites.changed
  service: name=nginx state=restarted
  sudo: yes
  tags:
    - nginx

- name: create user www paths
  file: >
    path=/var/www/{{ item }}
    owner={{ item }}
    group={{ item }}
    state=directory
  sudo: yes
  with_items:
    - sam
    - skylar

- include: 'site-borntyping.yml tags=sites,site-borntyping'
- include: 'site-eightbitgoggles.yml tags=sites,site-8bitgoggles'
