---
- name: install nginx
  apt: pkg=nginx state=latest
  sudo: yes

- name: configure sites
  sudo: yes
  template: >
    src=site-{{ item.key }}.conf
    dest=/etc/nginx/sites-available/{{ item.key }}.conf
    owner={{ item.value.user }}
    group={{ item.value.user }}
  with_dict: nginx_sites
  register: nginx_config

- name: enable sites
  sudo: yes
  file: >
    src=/etc/nginx/sites-available/{{ item.key }}.conf
    dest=/etc/nginx/sites-enabled/{{ item.key }}.conf
    state=link
    force=yes
  with_dict: nginx_sites
  register: nginx_enabled_sites

- name: restart nginx
  when: nginx_config.changed or nginx_enabled_sites.changed
  service: name=nginx state=restarted
  sudo: yes
