---
- name: install github-pages gem
  gem: name=github-pages state=latest user_install=yes
  tags:
    - ruby

- name: checkout borntyping site source
  git: >
    repo=git@github.com:borntyping/borntyping.github.io.git
    dest=/var/www/sam/borntyping
    version=master
    accept_hostkey=True
  register: site_borntyping_source

- name: build borntyping site using jekyll
  command: '{{ ansible_env.HOME }}/.gem/ruby/2.1.0/bin/jekyll build'
  args:
    chdir: /var/www/sam/borntyping
  when: site_borntyping_source.changed
